name: ${project.name}
main: com.poixson.ecotick.EcoTickPlugin
version: '${project.version}'
api-version: '${bukkit-short-version}'
depends:
  - pxnPluginLib
authors: lorenzop
website: ${project.url}
description: ${project.description}
