name: ${project.name}
main: com.poixson.ecotick.EcoTickPlugin
version: '${project.version}'
api-version: '${bukkit-short-version}'
dependencies:
    server:
        pxnPluginLib:
            load: BEFORE
            required: true
authors: lorenzop
website: ${project.url}
description: ${project.description}
