name: ${project.name}
main: com.poixson.ecotick.EcoTickPlugin
version: ${project.version}
api-version: ${spigot-short-version}
depend:
  - pxnCommonPluginMC
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
